version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/express-app
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: ec2-user